language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

services:
  - docker
install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  - wget https://github.com/simnibs/simnibs/releases/latest/download/environment_linux.yml
  - cat environment_linux.yml | grep -v pyopengl > env_linux.yml
  - conda env create --file env_linux.yml
  - pip install -f https://github.com/simnibs/simnibs/releases/latest simnibs
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - flake8 --max-line-length=115  # Enforce code style (but relax line length limit a bit).
  - make -C docs html  # Build the documentation.
